FROM nvcr.io/nvidia/pytorch:21.05-py3

# Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx libsm6 libxext6 libxrender1

# Install python dependencies
COPY requirements_yolov5.txt .
RUN python3 -m pip install --upgrade pip
RUN pip uninstall -y nvidia-tensorboard nvidia-tensorboard-plugin-dlprof
RUN pip install -r requirements_yolov5.txt 

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy contents
COPY . /usr/src/app

# Set environment variables
ENV HOME=/usr/src/app
# Expost the port
EXPOSE 5000

CMD ["python3", "test_api.py"]
