version: "2.3"
services:
    ai:
        container_name: obj_segmentation
        image: gradio_u2net:0.10.0
        restart: always 
        ports:
            - '5000:5000'
        runtime: nvidia
        environment: 
            DEPLOY_PORT: "18.224.154.80"
            DEPLOY_PORT: 5000
        volumes:
            - ./output:/usr/src/app/output